spring:
  application:
    name: user-reactor

  profiles:
    active: local

  r2dbc:
    url: r2dbc:mariadb://localhost:33308/reactor_wallet
    username: root
    password: password

  sql:
    init:
      schema-locations: classpath:db/mysql/schema.sql
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8083