spring:
  application:
    name: user-reactor

  profiles:
    active: local

  r2dbc:
    url: r2dbc:mariadb://localhost:33308/reactor_user
    username: root
    password: password
server:
  port: 8082