version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "33308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: my-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mariadb_data:
