spring:
  application:
    name: user-feign

  profiles:
    active: local

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33308/feign_user
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080