spring:
  application:
    name: wallet-feign

  profiles:
    active: local

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33308/feign_wallet
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081